# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d469d863464f6a22c5233b8d6343cef433aebbac3410ffeaa510af9f43b11c98792d063486bd4ece10ab6828d0994479b408f74153effa55545440179f10835

test:
  secret_key_base: ae2676e82cb5cef8ee40281a4fa88af2f634287ca56a9d4ea87b7703b6683e3b2e7af85f7961fb79b53ddca0949a2e68a33d47378203cd06d664060f50a37318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
